namespace: "helm"

configmap:
    name: "report-config"
    
deployment:
    name: "report-deployment"
    image: "nginx"
    tag: "latest"
    port: 80
    
service:
    name: "report-service"
    port: 81
    
ingress:
    name: "report-ingress"
    host: "report-viewer.com"
    path: "/(reports/)(.*)"
    
