---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logstash.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      tcp {
        port => {{ .Values.logstash.service.tcp.port }}
        codec => json_lines
      }
    }
    
    output {
      stdout {
        codec => rubydebug
      }
      
      elasticsearch {
        hosts => "http://{{ .Values.elasticsearch.service.name }}:9200"
      }      
    }

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.logstash.deployment.name }}
spec:
  selector:
    app: {{ .Values.logstash.deployment.name }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.logstash.service.api.port }}
      targetPort: {{ .Values.logstash.deployment.api.port }}
    - name: tcp-login
      protocol: TCP
      port: {{ .Values.logstash.service.tcp.port }}
      targetPort: {{ .Values.logstash.deployment.tcp.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.logstash.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.logstash.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.logstash.deployment.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.logstash.deployment.name }}
        tier: backend
    spec:
      containers:
      - name: logstash
        image: {{ .Values.logstash.deployment.image }}:{{ .Values.logstash.deployment.tag }}
        ports:
        - containerPort: {{ .Values.logstash.deployment.api.port }}
          name: api
          protocol: TCP
        - containerPort: {{ .Values.logstash.deployment.tcp.port }}
          name: tcp-login
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/config
        - name: logstash-pipeline-volume
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.logstash.configmap.name }}
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: {{ .Values.logstash.configmap.name }}
          items:
          - key: logstash.conf
            path: logstash.conf
